### ISSUE TITLE
Suggestion: beta.flathub.org support

### ISSUE THREAD

**Issue by HappiePlant** [CleoMenezesJr/flatline#1]
Hello!
I am using the https://beta.flathub.org instead of the flathub.org website because I find it a lot better. I was wondering if you could maybe add support for this site?
Thanks for reading!

**Comment by CleoMenezesJr** [comment]
Hey, thx for getting in touch.
Flatline has supported beta.flathub since day 1. Are you experiencing any issues?

**Comment by CleoMenezesJr** [comment]
I just looked and noticed that they actually changed how the button is shown, affecting the extension. It was expected since it's a beta. Thanks for letting me know.

**Comment by HappiePlant** [comment]
That's true, thanks for the reply!
