### ISSUE TITLE
addon not working on flathub

### ISSUE THREAD

**Issue by unicornsandcandies** [CleoMenezesJr/flatline#4]
I've seen that there's already a closed issue about not working on beta flathub. Recently flathub beta became the default flathub. Since then, addon is behaving exactly like in the mentioned issue. "Install" does nothing but downloads a flatpakref file

**Comment by CleoMenezesJr** [comment]
Hello, it's something I imagined would happen when I heard the news in the morning. By tomorrow, it will be fixed. Thanks for reporting.
